In [1]:
import numpy as np

In [2]:
myarr=np.array([3,2,5,8])

In [3]:
myarr

array([3, 2, 5, 8])

In [4]:
myarr[2]

5

In [5]:
myarr.dtype

dtype('int32')

In [6]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
listarray.shape

(3, 3)

In [9]:
listarray.size

9

In [10]:
zeros=np.zeros((3,3))

In [11]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
zeros.dtype

dtype('float64')

In [13]:
rng=np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
lspace=np.linspace(1,5,12)

In [16]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
arr=np.arange(99)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
arr=arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [21]:
arr=arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [22]:
arr.shape

(99,)

In [23]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [24]:
x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
ar=np.array(x)

In [26]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
ar.sum(axis=0)

array([12, 15, 18])

In [28]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [29]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [31]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [32]:
ar.ndim

2

In [33]:
one=np.array([5,6,22,4,1])

In [35]:
one.argmax()

2

In [36]:
one.argmin()

4

In [37]:
one.argsort()

array([4, 3, 0, 1, 2], dtype=int64)

In [38]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
ar.argmin()

0

In [40]:
ar.argmax()

8

In [42]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [44]:
ar2=np.array([[2,2,3],[4,5,7],[0,2,1]])

In [45]:
ar2

array([[2, 2, 3],
       [4, 5, 7],
       [0, 2, 1]])

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
ar2

array([[2, 2, 3],
       [4, 5, 7],
       [0, 2, 1]])

In [51]:
ar+ar2

array([[ 3,  4,  6],
       [ 8, 10, 13],
       [ 7, 10, 10]])

In [52]:
ar*ar2

array([[ 2,  4,  9],
       [16, 25, 42],
       [ 0, 16,  9]])

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
ar.sum()

45

In [55]:
ar.min()

1

In [56]:
ar.max()

9

In [57]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [58]:
np.count_nonzero(ar)

9

In [59]:
ar[1,2]=0

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 0],
       [7, 8, 9]])

In [61]:
np.count_nonzero(ar)

8

In [63]:
p_arr=[1,2,3,0]

In [64]:
p_arr

[1, 2, 3, 0]

In [65]:
np_arr=np.array(p_arr)

In [66]:
np_arr

array([1, 2, 3, 0])

In [67]:
np_arr.tolist()

[1, 2, 3, 0]